[package]
name = "milito-server-rs"
version = "0.1.0"
authors = ["Oleg Bask <spetz911@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
url = "2.1.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
